#!/bin/bash

# ~/.xinitrc is executed by startx which invokes xinit.
#
# If ~/.xinitrc is not present, /etc/X11/xinit/xinitrc is used.  On Debian,
# /etc/X11/xinit/xinitrc runs /etc/X11/Xsession which eventually runs
# ~/.xsession.  So, all customization should go in ~/.xsession as it's also read
# by display managers.
#
# We could remove this file and let xinit use /etc/X11/xinit/xinitrc, but I
# prefer the explicit call to source Xsession.

. /etc/X11/Xsession
