#!/bin/bash

# ~/.xsessionrc is invoked by all session types (Cinnamon, i3, ...)
# when logging in

# Prints a message for an information
function x11_print_info() {
  echo "INFO: $@"
}

# Prints a message for an error
function x11_print_error() {
  echo "ERROR: $@"
}

x11_print_info "Executing ~/.dotfiles/tag-linux/xsessionrc."

# Sets key bindings through xmodmap.
function x11_keys() {
  xmodmap_file="${HOME}/.config/X11/Xmodmap"
  if [[ -f "${xmodmap_file}" ]]; then
    x11_print_info 'Loading Xmodmap to modify keymaps and mouse mappings... '
    xmodmap "${xmodmap_file}" || x11_print_error 'Failed to run xmodmap.'
  else
    x11_print_info "Not loading xmodmap because file '${xmodmap_file}' not found."
  fi
}

# Sets key repeat rate.
function x11_keys_repeat() {
  local initial_delay=250
  local repeat_rate=50
  local message="Setting key repeat inital delay to ${initial_delay}ms with "
  message+="a repeat rate of ${repeat_rate}hz."
  x11_print_info "${message}"
  xset r rate $initial_delay $repeat_rate ||
    x11_print_error 'Failed to set keyboard repeat rate.'
}

# Loads Xresources files.
function x11_resources() {
  local xresources_file="${HOME}/.config/X11/.Xresources"
  if [[ -f "${xresources_file}" ]]; then
    x11_print_info 'Loading X resources...'
    xrdb -merge "${xresources_file}" ||
      x11_print_error 'Failed to load X resources.'
  else
    x11_print_info "Not merging xresources because file '${xresources_file}' not found."
  fi
}

# Loads system specific settings.
function x11_system_rc() {
  local system_rc_file="${HOME}/.config/X11/xsession-system_rc"
  if [[ -f "${system_rc_file}" ]]; then
    x11_print_info 'Loading system-specific (rc) X11 scripts...'
    source "${system_rc_file}" ||
      x11_print_error 'Failed to load system-specific (rc) X11 scripts.'
  else
    x11_print_info "Not loading system xsessionrc file because '${system_rc_file}' not found."
  fi
}

# Disables the audible bell.
xset -b

x11_keys
x11_keys_repeat
x11_resources
x11_system_rc

x11_print_info "Finished executing ~/.dotfiles/tag-linux/xsessionrc."
