#!/bin/bash

# necessary to make chrome pick up the proxy settings stored in gconf.
export DESKTOP_SESSION=gnome

# Key bindings
if [ -f $HOME/.xmodmaprc ]; then
    /usr/bin/xmodmap $HOME/.xmodmaprc
fi

userresources=$HOME/.Xresources

# Load .Xresources
if [ -f $userresources ]; then
    xrdb -merge "$userresources" &
fi

export OOO_FORCE_DESKTOP=gnome
export LANG="en_US.UTF-8"
export LC_ALL="en_US.UTF-8"
export LANGUAGE="en_US.UTF-8"
export LC_CTYPE="en_US.UTF-8"

# So i3 uses st instead of gnome-terminal
export TERMINAL="st"

# Start a terminal daemon
# if [[ -x /usr/bin/urxvtd ]]; then
#     /usr/bin/urxvtd --quiet --opendisplay --fork
# fi


if [[ -x /usr/bin/xbindkeys ]]; then
    xbindkeys 2> /dev/null &
fi

# Google drive
if [[ -x /opt/google/drive/drive-launcher.sh ]]; then
    /opt/google/drive/drive-launcher.sh &
fi

# fonts
if [[ -d /usr/local/google/home/jschaf/.local/share/fonts ]]; then
    xset -fp /usr/local/google/home/jschaf/.local/share/fonts
fi

if [[ -x /usr/bin/volumeicon ]]; then
    /usr/bin/volumeicon &
fi

# Set a background
# feh --bg-fill ~/.desktop.jpg

# Startup programs

type -P st > /dev/null && st -e "tmux new-session -A -s main"

if [[ -x /usr/bin/google-emacs ]]; then
    google-emacs &
elif [[ -x /usr/bin/emacs ]]; then
    emacs &
fi

# Enable zapping
# setxkbmap -option terminate:ctrl_alt_bksp

# Hide the cursor until it's moved
if [[ -x /usr/bin/unclutter ]]; then
    unclutter -idle 3 -root -jitter 10 &
fi

# Start the window manager
exec i3
