#!/bin/zsh

function iosource-list-file-paths-from-tmux-pane() {
  local pane_id="${1:=$TMUX_PANE}"
  if [[ -z "$TMUX"  ]]; then
    return 1
  fi
  tmux capture-pane -p -J -S '-' -t $pane_id |
    filter-filenames |
    tac |
    dedupe |
    replace-home-with-tilde |
    sed "\#^$(print -rD $PWD)\$#d" # Remove current directory.
}
iosource-list-file-paths-from-tmux-pane "$@"
