#!/bin/sh

# Key bindings.
if [[ -f "~/.config/X11/Xmodmap" ]]; then
    xmodmap "~/.config/X11/Xmodmap"
fi

# Load .Xresources.
if [[ -f "~/.config/X11/.Xresources" ]]; then
    xrdb -merge "~/.config/X11/.Xresources"
fi

# Ensures the font directory is indexed.
if [[ -d "$HOME/.local/share/fonts" ]]; then
  xset +fp "$HOME/.local/share/fonts"
fi

if [[ -f "~/.config/X11/xsession-system" ]]; then
    . "~/.config/X11/xsession-system"
fi

# Set key repeat inital delay to 250ms with a repeat rate of 50hz.
xset r rate 250 50

# Start the window manager.
exec i3
