#!/bin/zsh

# ~/.xinitrc is executed by xinit, usually invoked via startx.  startx is
# invoked after logging into a text console (TTY) and staring X11 manually.

# Sets key bindings.
if [[ -f "~/.config/X11/Xmodmap" ]]; then
  xmodmap "~/.config/X11/Xmodmap"
fi

# Loads .Xresources.
if [[ -f "~/.config/X11/.Xresources" ]]; then
  xrdb -merge "~/.config/X11/.Xresources"
fi

# Ensures the font directory is indexed.
if [[ -d "$HOME/.local/share/fonts" ]]; then
  xset +fp "$HOME/.local/share/fonts"
fi

# Loads system specific settings.
if [[ -f "$HOME/.config/X11/xsession-system" ]]; then
  . "$HOME/.config/X11/xsession-system"
fi

# Set key repeat inital delay to 250ms with a repeat rate of 50hz.
xset r rate 250 50

# Makes google-chrome pick up the proxy settings stored in gconf.
export DESKTOP_SESSION=gnome

# Disables the audible bell.
xset -b

# Start the window manager.
exec i3 > $HOME/.i3-error-log.txt 2>&1
