#!/bin/zsh

function widget-select-command() {
  setopt pipe_fail
  iosource-list-commands |
    $FZF_COMMAND --read0 --reverse --multi --header=Commands |
    join-input-by-space |
    insert-stdin-into-zsh-buffer
  widget-redisplay-propagate-error
}
widget-select-command "$@"
