#!/bin/zsh

# Selects files or directories from the current directory.
function widget-select-bazel-package() {
  setopt pipe_fail
  iosource-find-bazel-packages |
    $FZF_COMMAND --reverse --multi |
    join-input-by-space |
    insert-stdin-into-zsh-buffer
  widget-redisplay-propagate-error
}
