#!/bin/zsh

function widget-select-tmux-pane-urls() {
  if [[ -z "$TMUX"  ]]; then
    return 1
  fi
  local -a fzf_options
  fzf_options=(
    --reverse --multi
    --bind "alt-enter:execute(browse-url {})+abort"
  )
  tmux capture-pane -p -J -S '-' |
    filter-urls |
    tac |
    dedupe |
    $FZF_COMMAND $fzf_options[@] |
    join-input-by-space |
    insert-stdin-into-zsh-buffer

  widget-redisplay-propagate-error
}
widget-select-tmux-pane-urls "$@"
