#!/bin/zsh

function __widget-select-tmux-pane-urls() {
  if [[ -z "$TMUX"  ]]; then
    return 1
  fi
  local -a fzf_options
  fzf_options=(
    --reverse --multi
    --bind "alt-enter:execute(browse-url {})+abort"
  )
  tmux capture-pane -p -J -S '-' |
    filter-urls |
    tac |
    dedupe |
    $FZF_COMMAND $fzf_options[@] |
    join-input-by-space
  local ret=$?
  echo
  return $ret
}

function widget-select-tmux-pane-urls() {
  LBUFFER=${LBUFFER}$spacing$(__widget-select-tmux-pane-urls)
  local ret=$?
  zle redisplay
  zle zle-line-init
  return $ret
}

widget-select-tmux-pane-urls
