#!/bin/zsh


# Paste the selected command from history into the command line.
function widget-select-history() {
    setopt local_options no_glob_subst pipe_fail 2> /dev/null
    local -a fzf_options
    fzf_options=(
      --height=40%
      --tac
      --nth='2..,..'
      --tiebreak=index
      --bind=ctrl-r:toggle-sort
      --reverse
      --query=${LBUFFER}
      +m
    )

    local selected=$(fc -l 1 | $FZF_COMMAND $fzf_options[@])
    local ret=$?
    if [ -n "$selected" ]; then
      zle vi-fetch-history -n $selected
    fi
    zle redisplay
    typeset -f zle-line-init >/dev/null && zle zle-line-init
    return $ret
}
