#!/bin/zsh

# Paste the selected command from history into the command line.
function widget-select-history() {
    setopt pipe_fail
    local -a fzf_options
    fzf_options=(
      --tac
      --nth='2..,..'
      --tiebreak=index
      --bind=ctrl-r:toggle-sort
      --reverse
      +m
    )

    # The sed commands replaces \n with a newline.
    iosource-list-shell-history |
      $FZF_COMMAND $fzf_options[@] |
      sed 's#\\n#\
#g' |
      insert-stdin-into-zsh-buffer
    widget-redisplay-propagate-error
}
widget-select-history "$@"
