#!/bin/zsh

function widget-select-tmux-pane-files() {
  setopt pipe_fail
  iosource-list-file-paths-from-tmux-pane |
    $FZF_COMMAND --reverse --multi $@ |
    join-input-by-space |
    insert-stdin-into-zsh-buffer
  widget-redisplay-propagate-error
}
