#!/bin/zsh

function add-cwd-shell-bookmark() {
  local short_cwd="$(print -- $PWD | replace-home-with-tilde)"
  local bookmark_dir="$HOME/.zsh/shell-bookmarks"
  local bookmark_file="$bookmark_dir/default.txt"
  if [[ -e "$bookmark_dir/${HOST}.txt" ]]; then
    bookmark_file="$bookmark_dir/${HOST}.txt"
  fi
  if [[ "$short_cwd" == "~" ]]; then
    print -- "Skipping adding the home directory."
    return 0
  fi
  if grep --fixed-string --line-regexp -q "$short_cwd" "$bookmark_file"; then
    print -- "Already exists: '$short_cwd' in '$bookmark_file'."
    return 0
  fi
  print -- "Added '$short_cwd' to '$bookmark_file'."
  print -- "$short_cwd" >> "$bookmark_file"
}
add-cwd-shell-bookmark "$@"
