#!/bin/zsh

# Get path of current Bazel bin directory.
function bazel-bin-dir () {
  emulate -L zsh
  workspace_dir="$(bazel-workspace-dir)"
  if [[ -e "${workspace_dir}/bazel-bin" ]]; then
    echo "${workspace_dir}/bazel-bin"
  else
    bazel info bazel-bin
  fi
}
bazel-bin-dir "$@"
