#!/bin/zsh

# Get path of current Bazel workspace dir.
function bazel-workspace-dir () {
  if workspace_dir="$(find-parent-dir-containing-file MODULE.bazel)"; then
    echo "Can't find MODULE.bazel file in any parent directory."
    return 1
  fi
  echo "${workspace_dir}"
}
bazel-workspace-dir "$@"
