#!/bin/zsh

# Switches to a bookmarked directory after fuzzy finding it.
function cd-to-shell-bookmark() {
  local dest_dir=$(list-shell-bookmarks | dedupe | $FZF_COMMAND --reverse)
  if [[ $dest_dir != '' ]]; then
    dest_dir="${dest_dir/\~/$HOME}"
    builtin cd "${dest_dir}"
  fi
}
cd-to-shell-bookmark "$@"
