#!/bin/zsh

# clippaste - "Paste" data from clipboard to stdout
#
# Usage:
#
#   clippaste   - writes clipboard's contents to stdout
#
#   clippaste | <command>    - pastes contents and pipes it to another process
#
#   clippaste > <file>      - paste contents to a file
#
# Examples:
#
#   # Pipe to another process
#   clippaste | grep foo
#
#   # Paste to a file
#   clippaste > file.txt
function clippaste() {
    emulate -L zsh
    if is-darwin; then
      pbpaste
    elif is-cygwin; then
      cat /dev/clipboard
    else
        if command-exists xclip; then
          xclip -out -selection clipboard
        elif command-exists xsel; then
          xsel --clipboard --output
        else
            print "clipcopy: Platform $GRML_OSTYPE not supported or xclip/xsel not installed" >&2
            return 1
        fi
    fi
}
clippaste "$@"
