#!/bin/zsh

# Update the vendor/st repo.  It's special because it's origin is my github repo
# which has personal tweaks on the 'tweaks' branch.
function dotfiles-update-vendors-st() {
  pushd "${DOTFILES_VENDOR_DIR}/st" > /dev/null
  git checkout master
  git pull upstream master
  git push origin master
  git checkout tweaks
  git rebase origin/master
  git push -f origin tweaks
  popd > /dev/null
}
# Update submodules in ~/.dotfiles/vendor and commit the changes.
function dotfiles-update-vendors() {
  pushd "${DOTFILES_DIR}" > /dev/null
  git submodule update --init
  git submodule foreach git pull origin master
  dotfiles-update-vendors-st
  git add vendor
  git commit -m "chore(git): update submodules"
  popd > /dev/null
}

dotfiles-update-vendors
