#!/bin/zsh

set -o errexit pipefail

# Update the vendor/st repo.  It's special because it's origin is my github repo
# which has personal tweaks on the 'tweaks' branch.
function dotfiles-update-vendors-st() {
  pushd "${DOTFILES_VENDOR_DIR}/st" > /dev/null
  git checkout master
  git pull upstream master
  git push origin master
  git checkout tweaks
  git rebase origin/master
  git push origin tweaks
  popd > /dev/null
}
dotfiles-update-vendors-st "$@"
