#!/bin/zsh
# Update submodules in ~/.dotfiles/vendor and commit the changes.
function dotfiles-update-vendors() {
  pushd "${DOTFILES_DIR}" > /dev/null
  git submodule update --init
  git submodule foreach git pull origin master
  dotfiles-update-vendors-st
  git add vendor
  git commit -m "git: update submodules"
  popd > /dev/null
}
dotfiles-update-vendors "$@"
