#!/bin/zsh

# Google specific functionality.

# A Snippet Helper (ASH).  http://go/asnippethelper	
alias ash=/google/data/ro/projects/toolshed/ash.par

# Gets snippets for the last week.
function get-snippets() {
  # TODO: filter pub eng, and others
  # S cl/ to Submitted
  # V cl to Reviewed
  # P cl to Sent
  if [[ $(uname) == 'Darwin' ]]; then
    ssh jschaf "/google/data/ro/projects/toolshed/ash.par --critique \
      --calendar --event_status=accepted --mark_down --pending_cls --bugs \
      --assigned $@"
  else
    /google/data/ro/projects/toolshed/ash.par --critique --calendar \
      --event_status=accepted --mark_down --pending_cls --bugs --assigned "$@"
  fi
}

get-snippets "$@"
