#!/bin/zsh

# Show large objects in the current Git repository.
git-show-large-objects() {
  git rev-list --objects --all |
    git cat-file --batch-check='%(objecttype) %(objectname) %(objectsize) %(rest)' |  sed -n 's/^blob //p' |
    sort --numeric-sort --reverse --key=2 |
    cut -c 1-12,41- |
    gnumfmt --field=2 --to=iec-i --suffix=B --padding=7 --round=nearest
}

git-show-large-objects "$@"
