#!/bin/zsh

function init-fonts() {
    local font_dir="$HOME/.dotfiles/fonts"
    local font_data_dir
    if is-darwin; then
        font_data_dir="$HOME/Library/Fonts"
    else
        font_data_dir="$HOME/.local/share/fonts"
    fi

    print-info "Installing Consolas from $font_dir to $font_data_dir."
    cp -f $font_dir/*.ttf "$font_data_dir"

    if command-exists fc-cache; then
        print-info "Update font cache."
        fc-cache -v
    fi

}

init-fonts "$@"
