#!/bin/zsh

function init-fonts() {
  local font_dir="$HOME/.dotfiles-fonts"
  if [[ ! -d "${font_dir}" ]]; then
    git clone 'https://github.com/jschaf/dotfiles-fonts.git' "${font_dir}" || \
      return 1
  fi
  local font_data_dir="$HOME/.local/share/fonts"
  if is-darwin; then
    font_data_dir="$HOME/Library/Fonts"
  fi
  mkdir -p "$font_data_dir"

  print-info "Installing Consolas from $font_dir to $font_data_dir."
  cp -f $font_dir/*.ttf "$font_data_dir" || return 1

  if is-linux; then
    mkfontscale "$font_data_dir"
    mkfontdir "$font_data_dir"
  fi

  if command-exists fc-cache; then
    print-info "Updating font cache."
    fc-cache -v
  fi
}
