#!/bin/zsh


function init-wallpapers() {
  local wallpaper_dir="~/"
  if ! command-exists 'npm'; then
    print-error 'npm is not installed.'
    return 1
  fi

  if ! command-exists 'interfacelift-downloader'; then
    print-error 'interface-downlader is not installed.'
    print-info 'Hint: install interfacelift-downloader with:'
    print
    print-info 'npm install -g interfacelift-downloader'
    return 1
  fi

  mkdir -p "$WALLPAPER_HOME"
  # touch $WALLPAPER_HOME/empty_file.txt

  local wallpapers=$WALLPAPER_HOME/*
  local num_wallpapers=$#wallpapers
  if [[ $num_wallpapers -gt 800 ]]; then
    print-error "You already have over $num_wallpapers wallpapers"
    return 1
  fi

  local resolution="$(screen-resolution)"
  local download_limit=1000
  local message="Starting download of $download_limit wallpapers at "
  message+="resolution $resolution."
  print-info "$message"
  interfacelift-downloader "$resolution" "$WALLPAPER_HOME" "$download_limit"
  # rm -f $WALLPAPER_HOME/empty_file.txt
}

init-wallpapers "$@"
