#!/bin/zsh

# Inserts text into the ZSH buffer.
# Designed to handle vim mode.
# Must be called within a ZLE function.
function insert-text-into-zsh-buffer() {
  local insert_text="$1"
  local spacing=''
  if [[ $KEYMAP == 'vicmd' && ${RBUFFER[1]} != ' ' && -n $LBUFFER ]]; then
    spacing=' '
  fi
  LBUFFER="${LBUFFER}${RBUFFER[1]}${spacing}${insert_text}"
  RBUFFER="${RBUFFER[2,-1]}"
}
