#!/bin/zsh

# Locates the most recent config directory used by IntelliJ.
# See https://intellij-support.jetbrains.com/hc/en-us/articles/206544519-Directories-used-by-the-IDE-to-store-settings-caches-plugins-and-logs
function locate-most-recent-intellij-config-dir() {
  local dir_prefix=''
  local dir_suffix=''
  if is-macos; then
    dir_prefix="${HOME}/Library/Preferences/IntelliJIdea"
  elif is-linux; then
    dir_prefix="${HOME}/.IntelliJIdea"
    dir_suffix='/config'
  elif is-windows; then
    # NOTE: leading dot
    dir_prefix="${HOME}/.IntelliJIdea"
    dir_suffix='/config'
  elif is-windows; then
  else
    print-error 'Unknown OS when locating IntelliJ config dir: ${OS_TYPE}'
    return 1
  fi

  # Quote the directory to allow spaces, but don't quote the glob to
  # allow expansion.
  if test -n "$(find . -maxdepth 1 -name '${dir_prefix}*' -print -quit)"; then
    printf "%s${dir_suffix}\n" "${dir_prefix}"* |
      sort |
      tail -n 1
  else
    print-error "No IntelliJ template dirs matching ${dir_prefix}"
    return 1
  fi
}

locate-most-recent-intellij-config-dir "$@"
