#!/bin/zsh

function __make-hg-file-and-commit() {
  local identifier="$1"
  echo "$identifier" > "$identifier"
  hg add "$identifier"
  hg commit -m "Add $identifier."
}

function make-hg-experimental-repo() {
  local repo_dir="$HOME/tmp/hg-experiment-$[RANDOM % 100]"
  mkdir -p $repo_dir
  builtin cd "$repo_dir"

  hg init
  __make-hg-file-and-commit foo
  __make-hg-file-and-commit bar
  __make-hg-file-and-commit qux
  __make-hg-file-and-commit baz
}

make-hg-experimental-repo
