#!/bin/zsh

function update-emacs-buffers() {
  print-info "Reverting Emacs buffers."
  if emacsclient --no-wait --alternate-editor=false \
    --quiet --eval '(revbufs)'; then
    print-success "Emacs buffers updated."
  else
    print-error "emacs didn't revert buffers.  Is emacs started?"
  fi
}

function update-lesskey() {
  if command-exists lesskey && [[ -f "$HOME/.lesskey" ]]; then
    lesskey
  else
    print-error "Can't find lesskey or missing ~/.lesskey file."
  fi
}

# Command to get this workstation synchronized with the latest changes dotfile
# changes.
function open-sesame() {
  print-info "Welcome back! Lets get you up to speed..."
  local origDir="$PWD"
  echo
  if command-exists "open-sesame-host"; then
    open-sesame-host
  else
    print-info "No host specific open-sesame function found."
  fi
  echo
  update-lesskey
  echo
  update-git-repo "${DOTFILES_HOME}"
  echo
  update-git-repo "${HOME}/gdrive"
  echo
  update-emacs-buffers
  echo
  update-dotfiles-symlinks
  echo
  reload-zshrc
  echo
  print-success "You're five-by-five, good-to-go."
  pushd "${origDir}" > /dev/null
}

open-sesame "$@"
