#!/bin/zsh

function port-kill() {
  local port="$1"
  local pids
  # Simplest way to fill an array from a command. The results are whitespace
  # safe.
  # shellcheck disable=SC2207
  pids=( $(lsof -t -i:"${port}") )
  if [[ "${#pids[@]}" == 0 ]]; then
    echo 'No pids found on port' ${port}
    return 1
  fi

  print -- "Killing PIDs ${pids[*]} running on port ${port}..."
  for pid in "${pids[@]}"; do
    kill "${pid}"
  done
  printf ' done\n'
}
port-kill "$@"
