#!/bin/zsh

function port-kill() {
  local port="$1"
  local pid="$(lsof -t -i:${port})"
  if [[ -z "$pid" ]]; then
    return 1
  fi
  print -- "Killing PID ${port}..."
  lsof -i:${port}
  kill "${pid}"
}
