#!/bin/zsh

function port-kill() {
  local port="$1"
  local pids="$(lsof -t -i:${port})"
  if [[ -z "$pids" ]]; then
    echo 'No pids found on port' ${port}
    return 1
  fi

  print -- "Killing PIDs ${pids} running on port ${port}..."
  # lsof -i:${port}
  for pid in ${pids}; do
    kill "${pid}"
  done
}
port-kill "$@"
