#!/bin/zsh

# Starts a webserver from the current directory.
#
# @param [optional, Integer] bind port number, default 8080
serve() {
  local port=${1:-8080}
  local url="http://localhost:$port"
  if is-linux; then
    xdg-open $url
  elif is-darwin; then
    open $url
  fi
  http-serve.py $port
}

serve "$@"
