#!/bin/zsh

function tmux-smart-paste() {
  # -p prints to stdout
  local current_program=$(tmux display-message -p '#{window_name}')
  if [[ $current_program == 'zsh' ]]; then
    # insert with zle
  else

  fi

}
