#!/bin/zsh

# Return 0 if not uncommited changes, return 1 otherwise.
function git-repo-is-clean() {
  git diff-index --quiet HEAD --exit-code
}

# Given a file path, update the git repository at that path from origin/master.
# If the repository has local changes, stash the changes and pop them after
# git-pull completes.
function update-git-repo() {
  local repoDir="${1}"
  print-info "Updating git repository at ${repoDir}."
  if [[ ! -e "${repoDir}" ]]; then
    return
    print-error "Can't find repository at ${repoDir}."
  fi
  pushd "${repoDir}" >/dev/null
  if ! git-repo-is-clean; then
    print-error "Git repo at ${repoDir} is dirty. Not pulling changes."
    return 1
  fi
  git pull origin master
  popd >/dev/null
}

update-git-repo "$@"
