#!/bin/zsh

function update-dotfiles-symlinks() {
  print-info "Updating symlinks to ~/.dotfiles"
  if is-linux; then
    # Verbose so we see what got updated.
    # Never overwrite.
    yes n | rcup -v -t linux | grep -v identical
  else
    yes n | rcup -v | grep -v identical
  fi
  print-success "Symlinks updated."
}
update-dotfiles-symlinks "$@"
