#!/bin/zsh

function update-dotfiles-symlinks() {
  print-info "Updating symlinks to ~/.dotfiles"
  if is-linux; then
    # Verbose so we see what got updated.
    rcup -v -t linux || true
  else
    rcup -v || true
  fi
  print-success "Symlinks updated."
}
