#!/bin/zsh

# Retrieves weather information on the console.
# Usage example: 'weather san francisco'
function weather() {
  if [[ -z "$1" ]]; then
      curl wttr.in/mountain_view
  else
    args="$@"
    # Replace spaces with underscores.
    curl wttr.in/"${args:gs/ /_/}"
  fi
}
