#!/bin/zsh

function wifi-password-mac() {
  local wifi_ssid="$1"
  if [[ -z $wifi_ssid ]]; then
    # https://stackoverflow.com/questions/4481005
    wifi_ssid=$(
      airport -I |
        awk '/ SSID/ {print substr($0, index($0, $2))}')
  fi
  # Password is printed on stderr with -g.
  # https://apple.stackexchange.com/questions/176119
  local wifi_password=$(security find-generic-password \
                                 -D 'AirPort network password' \
                                 -a "$wifi_ssid" -g  2>&1 >/dev/null)

  echo "ssid: \"$wifi_ssid\""
  echo "$wifi_password"
}

function wifi-password() {
  local wifi_ssid="$1"
  if is-darwin; then
    wifi-password-mac "$wifi_ssid"
  fi
}

wifi-password "$@"
