#!/bin/bash

# Given a decimal number start and end print all unicode codepoint.
function print-decimal-unicode-range() {
    local start="$1"
    local end="$2"
    local allChars=""
    for decimalCode in $(seq "${start}" "${end}"); do
        local hexCode=$(printf '%x' "${decimalCode}")
        allChars+="\u${decimalCode}"
    done
    printf "${allChars}"
}

function print-unicode-range() {
    local start="$1"
    local end="$2"

    local startDecimal=$((16#$start))
    local endDecimal=$((16#$end))
    local allChars=""
    for decimalCode in $(seq "${startDecimal}" "${endDecimal}"); do
        local hexCode=$(printf '%x' "${decimalCode}")
        allChars+="\u${hexCode}"
    done
    printf "${allChars}"
}

function test-fonts-powerline() {
    printf "Powerline fonts glyps:\n"
    printf "\ue0b0 \u00b1 \ue0a0 \u27a6 \u2718 \u26a1 \u2699 \ue0b1 \ue0b2 \ue0b3\n"
}


function test-fonts-font-awesome() {
    printf "Font Awesome glyps:\n"
    printf "\uf2b4 \uf119 \uf1a0 \uf23b \uf087 \uf155\n"
}

function test-nerd-patched-fonts() {
    echo "Pomicons:"
    print-unicode-range e000 e00a
    echo
    
    echo "Pomicons:"
    print-unicode-range e000 e00a
}


function test-fonts() {
    test-fonts-powerline
    printf '\n'
    test-fonts-font-awesome
}
