#!/bin/bash
# This hook is run after a new virtualenv is activated.

proj_name=$(basename "$VIRTUAL_ENV")
proj_path="$PROJECT_HOME/$proj_name"
mkdir -p "$proj_path"
add2virtualenv "$proj_path"
cd "$proj_path"
