#!/bin/zsh

# IntelliJ stores config options in different places depending on the
# environment.  From the docs at
# https://www.jetbrains.com/help/idea/sharing-live-templates.html#config_file_location
#
# Windows: ~/.IntelliJ IDEA<version_number>/config/templates
# Linux: ~/IntelliJ IDEA<version>/config/templates
# macOS: ~/Library/Preferences/IntelliJ IDEA<version>/templates

# init-intellij-live-template-config "$@"
